apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: aspen-api-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: aspen-api
  updatePolicy:
    updateMode: "Off"

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: aspen-api
  namespace: {{ name }}
  labels: 
    app: aspen-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspen-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aspen-api
    spec:
      containers:
      - image: {{ api_image }}
        name: aspen-api
        volumeMounts:
          - mountPath: "/app/ssl/certs"
            name: uaf-db-ssl-certs
            readOnly: true
          - mountPath: "/app/ssl/private"
            name: uaf-db-ssl-key
            readOnly: true
        ports:
        - containerPort: 80 
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: uaf-db-auth
              key: dbname
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: uaf-db-auth
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: uaf-db-auth
              key: password
        - name: DefaultConnection
          value: "sslmode=verify-ca; sslrootcert=/app/ssl/certs/uaf-server-ca.pem; sslcert=/app/ssl/certs/uaf-client-cert.pem; sslkey=/app/ssl/private/uaf-client-key.pem; hostaddr=10.101.160.3; port=5432; user=$POSTGRES_USER; dbname=$POSTGRES_DB; password=$POSTGRES_PASSWORD"
      volumes:
        - name: uaf-db-ssl-certs
          secret:
            secretName: uaf-db-ssl-certs
        - name: uaf-db-ssl-key
          secret:
            secretName: uaf-db-ssl-key
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: aspen-api-service
  namespace: {{ name }}
  labels:
    app: aspen-api-service
spec:
  selector:
    app: aspen-api
  type:  ClusterIP
  ports:
  - port: 80
    protocol: TCP
---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
  name: aspen-api-ingress
spec:
  rules:
  - host: {{ ingress }}
    http:
      paths:
      - path: /
        backend:
          serviceName: aspen-api-service
          servicePort: 80
  tls:
  - hosts:
    - {{ ingress }}
    secretName: {{ ingress }}-cert
