apiVersion: apps/v1
kind: Deployment
metadata: 
  name: aspen-api
  namespace: {{ name }}
  labels: 
    app: aspen-api
spec:
  spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspen-api
  template:
    metadata:
      labels:
        app: aspen-api
    spec:
      containers:
      - name: aspen-api
        image: {{ api_image }}
        ports:
        - containerPort: 80 
        env:
          # hack: replace with reall connection string
        - name: DefaultConnection
          value: "Server=postgres-service; Port=5432; Database=aspen; User ID=aspen; Password=aspen;"
---
apiVersion: v1
kind: Service
metadata:
  name: aspen-api-service
  namespace: {{ name }}
  labels:
    app: aspen-api-service
spec:
  selector:
    app: aspen-api
  type:  ClusterIP
  ports:
  - port: 80
    protocol: TCP
---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
  name: aspen-api-ingress
spec:
  rules:
  - host: {{ ingress }}
    http:
      paths:
      - path: /
        backend:
          serviceName: aspen-api-service
          servicePort: 80
  tls:
  - hosts:
    - {{ ingress }}
    secretName: {{ ingress }}-cert