apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ name }}
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12.2
        ports:
        - containerPort: 5432
        env:
        # hack: replace with real secrets
        - name: POSTGRES_USER
          value: aspen
        - name: POSTGRES_PASSWORD
          value: aspen
        - name: POSTGRES_DB
          value: aspen
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ name }}
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  type:  ClusterIP
  ports:
  - port: 5432
    protocol: TCP