apiVersion: apps/v1
kind: Deployment
metadata: 
  name: aspen-web
  namespace: {{ name }}
  labels: 
    app: aspen-web
spec:
  spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspen-web
  template:
    metadata:
      labels:
        app: aspen-web
    spec:
      containers:
      - name: aspen-web
        image: {{ web_image }}
        ports:
        - containerPort: 3000
        #hack replace with the real api url and the name of the real domain where this is hosted
        env:
        - name: REACT_APP_GLOBAL_ADMIN_DOMAIN 
          value: aspen
        - name: REACT_APP_API_URL 
          value: localhost
---
kind: Service
apiVersion: v1
metadata:
  name: aspen-web-service
  namespace: {{ name }}
  labels:
    app: aspen-web-service
spec:
  selector:
    app: aspen-web
  type:  ClusterIP
  ports:
  - name:  http
    port: 80
    protocol: TCP
    targetPort: 3000  
---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
  name: aspen-web-ingress
spec:
  rules:
  - host: {{ ingress }}
    http:
      paths:
      - path: /
        backend:
          serviceName: aspen-web-service
          servicePort: 80
  tls:
  - hosts:
    - {{ ingress }}
    secretName: {{ ingress }}-cert
