version: "2"
services:
  aspen_database:
    image: postgres
    container_name: aspen_database
    environment:
      - POSTGRES_USER=Aspen
      - POSTGRES_PASSWORD=Aspen
      - POSTGRES_DB=Aspen
    volumes:
      - ./pgsql/:/docker-entrypoint-initdb.d/
      - database:/var/lib/postgresql/data/
    networks:
      - internal

  aspen_api:
    build:
      context: .
      dockerfile: aspen.api/Dockerfile
    container_name: aspen_api
    environment: 
      - DefaultConnection="Server=localhost; Port=5432; Database=Aspen; User ID=Aspen; Password=Aspen;"
    # ports:
    #   - 80:80
    #   - 443:443
    networks:
      - internal

  aspen_web:
    build:
      context: aspen.web
    container_name: aspen_web
    ports:
      - 80:80
      - 443:443
      - 3000:3000
    environment:
      - REACT_APP_GLOBAL_ADMIN_DOMAIN=aspen
      - REACT_APP_API_URL=aspen_api
    networks:
      - internal

networks:
  internal:

volumes:
  database:
