version: '3'
services:

  database:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_USER=Aspen
      - POSTGRES_PASSWORD=Aspen
      - POSTGRES_DB=Admin
      - PGPASSFILE=blank
    ports: 
      - 5432:5432
    expose:
      - 5432
    networks:
      internal:

  api:
    build:
      context: .
      dockerfile: aspen.api/Dockerfile
    container_name: api
    depends_on: 
      - database
    environment: 
      - DefaultConnection=Server=database; Port=5432; Database=Admin; Username=Aspen; Password=Aspen;
    ports:
       - 5000:5000
      #  - 443:443
    networks:
      internal:

  web:
    build:
      context: aspen.web
    container_name: web
    ports:
      - 3000:3000
    environment:
      - REACT_APP_GLOBAL_ADMIN_DOMAIN=aspen
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      internal:

networks:
  internal: