version: "2"
services: 
    aspen_database:
        image: postgres
        container_name: aspen_database
        environment:
            - POSTGRES_USER=Aspen
            - POSTGRES_PASSWORD=Aspen
            - POSTGRES_DB=Aspen
        volumes:
            - ./pgsql/:/docker-entrypoint-initdb.d/
            - database:/var/lib/postgresql/data/
        networks:
            - internal

    aspen_api:
        build: .
        image: aspen_api/
        container_name: aspen_api
        ports: 
            - 80:80
            - 443:443
        networks: 
            - internal
   
networks:
    internal:

volumes: 
    database: