name: Run Tests
on: [push]
jobs:
  update-infrastructure:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - run: |
          cd ops/testing
          DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build --parallel --pull
          docker-compose up -d
          docker-compose exec -T api_test dotnet test
          docker-compose exec -T web_test npm run test -- -- watchAll=false

      - run: |
          cd ops/testing
          docker-compose down