name: run-tests-for-pull-request

on:
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: build and test
        run: |
          cd ops
          DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build --parallel --pull
          docker-compose up -d
          docker-compose exec -T api_test dotnet test
          docker-compose exec -T web_test npm run test -- --watchAll=false
